steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/api/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/staging'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/staging'

images:
  - 'gcr.io/$PROJECT_ID/staging'
